services:
  - type: web
    name: gestionlabo-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USE_SQLITE_DEV
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 480
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 30
      - key: DATABASE_URL
        fromDatabase:
          name: gestionlabo-db
          property: connectionString

databases:
  - name: gestionlabo-db
    databaseName: gestionlabo
    user: gestionlabo
